name: Checks
on: pull_request
jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install npm dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn run lint
      - name: Build
        run: npm run build